#################################################
# Browser
#################################################

browser=chromium

headless=false

timeout=30000

slowMo=100

#################################################
# Environment
#################################################

environment=qa

#################################################
# Reporting
#################################################

video=true

trace=true

screenshot=true